services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.2.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=netology-test
    ports:
      - "9200:9200"
    networks:
      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic-net

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - /tmp/nginx_logs:/var/log/nginx
    networks:
      - elastic-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.2.3
    container_name: filebeat
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /tmp/nginx_logs:/var/log/nginx:ro
    depends_on:
      - elasticsearch
      - nginx
    networks:
      - elastic-net

networks:
  elastic-net:
    driver: bridge
